{% set name = "pynauty" %}
{% set version = "1.1.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pynauty-{{ version }}.tar.gz
  sha256: fca00e50874b0cb34800f41b91b31f4b61a6ec22f2d3bd0b2290209b8d552307
  patches:
    - setup.patch

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - pip
    - python
    - nauty =2.7.1
  run:
    - python
    - {{ pin_compatible('nauty', max_pin='x.x.x') }}

test:
  imports:
    - pynauty
    - pynauty.graph
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pdobsan/pynauty
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: Isomorphism testing and automorphisms of graphs
  description: |
    Pynauty can be used to compare graphs for isomorphism and to determine
    their automorphism group in a Python programming environment. Pynauty
    is a Python/C extension module using library components from the Nauty
    package by Brendan McKay.
  doc_url: https://github.com/pdobsan/pynauty
  dev_url: https://github.com/pdobsan/pynauty

extra:
  recipe-maintainers:
    - jan-janssen
